### PR TITLE
Remove application form and update language

### PR DESCRIPTION
**Pull request by cosden**
Updated to remove link (which has been closed for a few weeks).

### CODE REVIEW

**Comment by danielskatz** [comment]
I'm not sure about 
> We are not able to offer a remote or hybrid option, however, we do anticipate
 being able to offer some degree of asynchronous participation remotely both
 before and after the workshop.
 
 what does this actually mean?

**Comment by cosden** [comment]
It means that you can contribute to topics/ideas to be addressed (we can put out a call ahead of time to seed the workshop). And afterwards, we hope to have most of the deliverables at 80% with an "owner." The last 20% I figured people who weren't there can/should be able to contribute. 

But I'm also fine removing it entirely if it's confusing or misleading. It's not that important.

**Comment by danielskatz** [comment]
I think we either need to say more about it (like what you wrote in your response) or nothing about it.  Right now, it's unclear.

**Comment by cosden** [comment]
OK. Thanks @danielskatz. I removed just the part about participation before/after. I think it's best to say nothing.

**Comment by cosden** [comment]
I'm going to go with it. We can revisit to improve if needed!

**Pull request merged**
